language: cpp
dist: trusty
compiler:
  - gcc
virtualenv:
    system_site_packages: true
      - "2.7_with_system_site_packages"
notifications:
  email:
    recipients:
      - remi.cailletaud@3sr-grenoble.fr
    on_success: change
    on_failure: always
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install cmake git freeglut3-dev libloki-dev libboost-all-dev fakeroot dpkg-dev build-essential g++ python-dev ipython python-matplotlib libsqlite3-dev python-numpy python-tk gnuplot libgts-dev python-pygraphviz libvtk6-dev python-numpy libeigen3-dev python-xlib python-qt4 pyqt4-dev-tools gtk2-engines-pixbuf python-argparse libqglviewer-dev python-imaging libjs-jquery python-sphinx python-git python-bibtex libxmu-dev libxi-dev libcgal-dev help2man libbz2-dev zlib1g-dev python-minieigen
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS=-frounding-math -DCMAKE_INSTALL_PREFIX=./../inst -DSUFFIX=-trunk ..
script:
  - make
  - make install
  - ./../inst/bin/yade-trunk --test
  - ./../inst/bin/yade-trunk --check
